### ISSUE TITLE
I Have Copied The code from github 

### ISSUE THREAD

**Issue by vedant-achh** [ski043/marshal-ui-yt#2]
but when i signup user doesnt get created in the database

**Comment by ski043** [comment]
3 things you should remember for your future:
1: GitHub issues are for issues and not for people that are too lazy to watch a video where I explain everything.
2: There is like an 8-hour video where I show how to do everything… 
3: How about a: "Hey, thank you for the code... bla bla bla"

Btw. user is not in your db because you haven't watched the video and therefore probably set up the .envs incorrectly.
